### ISSUE TITLE
Run action on selected resource on button click?

### ISSUE THREAD

**Issue by HeadStudios** [dnwjn/nova-button#27]
Is it possible to run an action on a button click for the resource? Thank you!

**Comment by HeadStudios** [comment]
Also any input on why the event is not being triggered? Video for context:
https://share.getcloudapp.com/xQuReE09

I did create the Event Service Provider array add 
https://gist.github.com/HeadStudios/974d653feba343e0ff19ef082aef05b3

listener:
https://gist.github.com/HeadStudios/4e834f4cb23fa1dc645b8695674ac6e6

**Comment by dnwjn** [comment]
Hi @HeadStudios and thank you for reporting your issue in such an extensive way! That made it so easy for me reproduce!

It turns out that this is caused by the previous release (assuming you're using v4). I am fixing this as we speak and will release a patch directly after. If you update to that version it should work directly, because you've set up everything correctly!

I'll let you know when the update is released!

I also want to add that the button click triggers the `ButtonClick` event by default. You can use `->event()` to override that event, but if you don't it's just the default one.

**Comment by dnwjn** [comment]
@HeadStudios 4.1.1 is now live and contains a fix for your issue!

If it doesn't fix your issue please feel free to reopen this ticket.

Thank you for reporting it!
