### ISSUE TITLE
Experiencing form submission error with button on create page

### ISSUE THREAD

**Issue by ReinardGans** [dnwjn/nova-button#38]
I currently have this form submission page with a validation button which should execute some logic when clicked. (see view below) However, when submitting the form I receive an error and are unable to submit the form. The only error I receive is on the UI and it reads: "There was a problem submitting the form"

Here is the code for my button:

```
  Button::make('Validate')
      ->style('primary')
      ->label('Validate')
      ->hideFromIndex()
      ->showOnCreating()
      ->showOnUpdating(),
```

![FormSubmisison](https://github.com/dnwjn/nova-button/assets/85315092/b7b5de63-5d29-431e-8e05-d6586fe6ac0c)

**Comment by dnwjn** [comment]
Hi @ReinardGans!

Could you provide me with some more information, such as:
* Laravel version
* Nova version
* The full resource you're trying to use this in

Thanks!

**Comment by dnwjn** [comment]
> Hi @dnwjn I am currently using "dnwjn/nova-button": "4.0", "laravel/nova": "~4.0", and Laravel Framework 10.43.0 . Also, I have added the fill resource in a zip file below. [DataAttribute.zip](https://github.com/dnwjn/nova-button/files/14385881/DataAttribute.zip)

I've set up a fresh Laravel project with Nova and this package, using the versions you mentioned. I'm unable to reproduce your issue. I've also gone through your Nova resource but I'm not seeing anything weird. Because of this I'm not finding any reason it's caused by this package.

Have you tried submitting the form with all fields removed except the button, and then slowly adding the other fields one by one? Maybe it's caused by another field, or maybe another field doesn't play nicely with the button. It's hard for me to tell.
